### PR TITLE
[CS] round structure

### PR DESCRIPTION
**Pull request by tomaas-zeman**
cs-11

### CODE REVIEW

**Comment by tomaas-zeman** [comment]
@qwrtln @DarthGandalf Any ideas what to do with the accented character in the section's name?

Screenshot 2024-06-09 at 13 59 19

It's `Ů` but it gets replaced with weirdly accented `O`. I tried `\r{u}` but the resulted in the same bad character

**Comment by DarthGandalf** [comment]
Ah, a variation of this issue is precisely why we had to switch to TTF font + LuaLaTeX for cyrillic languages. You can try the same for Czech (flip a bool in the workflow, some build.sh scripts, and look in main_ru.tex for the font setup)

**Comment by qwrtln** [comment]
If nothing else works, you can just redefine `\r{u}`. But it might not work with uppercasing.

**Comment by tomaas-zeman** [comment]
Switching to luapdf produced a different error

```
  Missing character: There is no ř (U+0159) in font ec-lmr12!
  Missing character: There is no ů (U+016F) in font ec-lmr12!
  Missing character: There is no ž (U+017E) in font ec-lmr12!
  Missing character: There is no ř (U+0159) in font ec-lmr12!
  Missing character: There is no ě (U+011B) in font ec-lmr12!
  Missing character: There is no ě (U+011B) in font ec-lmr12!
  Missing character: There is no ě (U+011B) in font ec-lmr12!
```

**Comment by DarthGandalf** [comment]
Yes, the setup in main_ru.tex contains everything needed

**Comment by tomaas-zeman** [comment]
Apart from the section title which now has a slighly different font, everything looks good. I don't mind the different font, it still looks good

**Review by qwrtln — APPROVED** [review]

**Comment by qwrtln** [comment]
Oh no, @Heegu-sama, need your help again with the checks.

**Pull request merged**
