### PR TITLE
[FR] components

### PR DESCRIPTION
**Pull request by Gastonia02**
fr-06
fr-07

### CODE REVIEW

**Comment by qwrtln** [comment]
po4a check

**Review by qwrtln — CHANGES_REQUESTED** [review]
CI failed, here's how to fix it:
1. Please use `tools/make_printable.sh fr` script to see the printable build. Hero figures and battlefield obstacles are pushed to another page. Please use the new `\iftoggle{printable}` mechanism to reduce the size of some components, to make them fit in the build. You can see it already in use for Round Tracker. For Polish, I shrunk the dice and battlefield board. You can see it in `pl.po` file, if you like.
2. Fix the rest of the fuzzy strings, as this section introduced quite a number of them. Use `tools/find_fuzzy.sh fr` script to find them.
3. po4a - you know what to do :-)

**Comment by Gastonia02** [comment]
po4a check

**Comment by Gastonia02** [comment]
po4a commit

**Comment by qwrtln** [comment]
Two more things:
1. Please change French entry in Readme to 100%. You've earned it ;-)
2. The grail token hyperlink seems to be broken. Can you fix it?

**Comment by qwrtln** [comment]
I can see that the grail hypertarget in all map locations is missing in `fr.po` file.

**Review by qwrtln — APPROVED** [review]
🎉 🎊 🚀

**Pull request merged**
