### PR TITLE
[HE] player_turns

### PR DESCRIPTION
**Pull request by davidpodless**
That's the last section I translated before the first PR

### CODE REVIEW

**Comment by davidpodless** [comment]
image

image

image

**Comment by qwrtln** [comment]
That sole line before Necropolis note box doesn't look good. Can you do anything about it?

**Comment by davidpodless** [comment]
> That sole line before Necropolis note box doesn't look good. Can you do anything about it?

The only thing I can think of is to add few \n between sections. 

let's try and see how it will look

**Comment by davidpodless** [comment]
> > That sole line before Necropolis note box doesn't look good. Can you do anything about it?
> 
> The only thing I can think of is to add few \n between sections.
> 
> let's try and see how it will look

Hmmmmmm it looks like it ignored \n in the section all over the place
I need to check if that's across all sections

**Comment by DarthGandalf** [comment]
I think \n is called \par here (paragraph). Or maybe some \vspace will help, no idea

**Comment by davidpodless** [comment]
\\\\ is the key here

he-12
he-13
he-14

**Comment by qwrtln** [comment]
Actually, it would be better to shorten the text, so that the orphaned line is not in the next column, not adding newlines to produce two orphans.

**Comment by davidpodless** [comment]
Hmm 🤔 
Ok, I'll try but I fear it will break the whole structure of the page

Let's see what happens

**Comment by davidpodless** [comment]
what do you think?

he-12
he-13
he-14

**Comment by qwrtln** [comment]
Better!

**Review by qwrtln — APPROVED** [review]

**Pull request merged**
