### PR TITLE
Linkify more links in printable

### PR DESCRIPTION
**Pull request by DarthGandalf**
Why is there such list at all, instead of replacing all hyperlink with pagelink?

### CODE REVIEW

**Comment by qwrtln** [comment]
Firstly, if you'd like to use all the hyperlinks, it's better to get rid of the script altogether. Secondly, did you try building this? Appending page number to every single hyperlink produced so much text, that the layout kept breaking.

**Comment by DarthGandalf** [comment]
Yes, it builds and looks correct. Layout broke on which page for you?

**Comment by qwrtln** [comment]
No page in particular. The build was automatic, so it kept breaking from time to time. Fixing it by hand was a nightmare. If you let it running like that, it will keep breaking until somebody notices it. We noticed that limiting those hyperlinks gives consistent results.
You think it's more readable with all hyperlinks appended with page numbers?

**Comment by DarthGandalf** [comment]
>  You think it's more readable with all hyperlinks appended with page numbers?

For the printed version, yes. Otherwise, I need to mentally figure out what the topic could be, and find it either in TOC, or in index.

**Comment by qwrtln** [comment]
Let's park this for now.

**Pull request closed without merging**
