### PR TITLE
[HE] combat

### PR DESCRIPTION
**Pull request by davidpodless**
New version for combat translated to He

Minus page 34, it looks fine to me

What do you think?

he-31
he-32
he-33
he-34
he-35
he-36

### CODE REVIEW

**Comment by qwrtln** [comment]
Crazy idea: maybe try putting the gremlin above ניסיון קרב but anchor it to the page bottom, like it is now on page 34. It will move the whole paragraph to the next page.
It will keep page 33 fairly occupied, while still having page 34 with at least a couple of paragraphs.

I don't think there's a "right" way of fixing this. You need to work around the original layout to make the translation look good.

**Comment by DarthGandalf** [comment]
Something broke here under the Arrow Tower card. Is "Ar-.... row tower" supposed to be like this?

**Comment by davidpodless** [comment]
> Something broke here under the Arrow Tower card. Is "Ar-.... row tower" supposed to be like this?

it is the normal breaking word in English, but I agree it looks bad
I'll try to make it all in one line

**Comment by DarthGandalf** [comment]
Re 34: I agree with @qwrtln about moving gremlin there

**Comment by qwrtln** [comment]
> How do I do it?
> 
> I tried to add it to another section - it didn't work
> 
> I tried to move the location of the gremlin msgid - it returned it to the original place

You can't change the original structure, as it won't work. Remember that po4a reconstructs the translated document based on the positions of the `msgid` in the original. Try something like this:

```po
#. type: multicols
#: sections/combat.tex:141
#, no-wrap
msgid ""
"\\subsection*{\\pagetarget{Combatexperience}{Combat Experience}}\n"
"\n"
msgstr ""
"\\vspace*{\\fill}\n"
"\\hspace{-2em}\\includegraphics[width=\\linewidth]{\\art/gremlin.png}\n"
"\n"
"\\subsection*{\\pagetarget{Combatexperience}{ניסיון קרב}}\n"
"\n"
```

Glue it to an existing `msgid`.

**Comment by davidpodless** [comment]
> > How do I do it?
> > I tried to add it to another section - it didn't work
> > I tried to move the location of the gremlin msgid - it returned it to the original place
> 
> You can't change the original structure, as it won't work. Remember that po4a reconstructs the translated document based on the positions of the `msgid` in the original. Try something like this:
> 
> ```po
> #. type: multicols
> #: sections/combat.tex:141
> #, no-wrap
> msgid ""
> "\\subsection*{\\pagetarget{Combatexperience}{Combat Experience}}\n"
> "\n"
> msgstr ""
> "\\vspace*{\\fill}\n"
> "\\hspace{-2em}\\includegraphics[width=\\linewidth]{\\art/gremlin.png}\n"
> "\n"
> "\\subsection*{\\pagetarget{Combatexperience}{ניסיון קרב}}\n"
> "\n"
> ```
> 
> Glue it to an existing `msgid`.

That's will give me 2 gremlins since if there won't be anything in the msgid of the gremlin it will add it regardless

**Comment by qwrtln** [comment]
> That's will give me 2 gremlins since if there won't be anything in the msgid of the gremlin it will add it regardless

No problem, just add a dummy translation to the actual gremlin. You can use `\phantom{}` for this.

**Comment by DarthGandalf** [comment]
These poor dogs were moved quite a lot

**Review by DarthGandalf — APPROVED** [review]

**Comment by davidpodless** [comment]
> Yeah, OK. Maybe flip them vertically, so that they're not eating away the neighbouring paragraph ;-)

IDK, it looks weirder now
What do you think?

he-33

**Comment by davidpodless** [comment]
he-33

like this?

**Comment by qwrtln** [comment]
Yeah, LGTM. If you prefer them facing the other way, then change it back, but `\hspace` is not necessary in any case.

**Comment by qwrtln** [comment]
Or, if you do flip them back, maybe introduce positive hspace, because they were originally in the left column. Experiment and decide what looks best.

**Comment by qwrtln** [comment]
Well, looks like you've reached 100%. Cogratz 🎉

**Pull request merged**
