### PR TITLE
Replace images with LaTeX circles

### PR DESCRIPTION
**Pull request by DarthGandalf**
This will help with translations, because they only need to replace the card image with the localized image.

en-19
en-20
en-38
en-28
en-07

### CODE REVIEW

**Comment by qwrtln** [comment]
Oh boy, this is going to be tough on translators. Luckily, only the French crew is left to fix it. In any case, good step forward.

pl-07
pl-19
pl-20
pl-28
pl-38

**Comment by qwrtln** [comment]
@Gastonia02 can you fix it for French?

**Comment by DarthGandalf** [comment]
> Oh boy, this is going to be tough on translators.

This is somewhat tedious, but it's actually easier for me, because updating all the translations follows the same pattern. Except for French because I don't want to add circles on top of circles. And for Hebrew because I don't dare touching it due to being confused by interaction between LTR and RTL.

**Comment by DarthGandalf** [comment]
This is good enough for now. I didn't reconstruct example images yet, only cards. Maybe later.

**Review by qwrtln — APPROVED** [review]

**Review by Heegu-sama — APPROVED** [review]

**Pull request merged**
