### PR TITLE
Readme for 1.2

### PR DESCRIPTION
**Pull request by qwrtln**
Standard before|after picture below. I'm open to suggestions regarding emojis.
image

### CODE REVIEW

**Comment by evilmint** [comment]
imo there's a mess with the emojis, maybe instead of the col+row combination in the cells, just put a <a href="...">Download</a> link ?

**Comment by qwrtln** [comment]
> imo there's a mess with the emojis, maybe instead of the col+row combination in the cells, just put a [Download](...) link ?

Fixed

**Comment by JStanula** [comment]
I would put something like "stable_PL" "beta_EN"

**Comment by qwrtln** [comment]
> I would put something like "stable_PL" "beta_EN"

Where exactly? Can you give me 4 names for EN and PL each?

**Comment by JStanula** [comment]
I mean instead of "download"

**Review by DarthGandalf — APPROVED** [review]

**Pull request merged**
