### PR TITLE
[HE] credits

### PR DESCRIPTION
**Pull request by davidpodless**
I don't think it is right to try and write the names in Hebrew letters.

he-52

### CODE REVIEW

**Review by qwrtln — APPROVED** [review]
Suit yourself, LGTM.

**Comment by qwrtln** [comment]
Oh, BTW, there's a text regarding GitHub in `main_he.tex`, mind translating that too?

**Comment by davidpodless** [comment]
> Oh, BTW, there's a text regarding GitHub in `main_he.tex`, mind translating that too?

I must have missed it... I'll do it now

**Comment by DarthGandalf** [comment]
The hyphenation (Bar-tosz) and newlines inside names look weird to me. Would it look any better to disallow hyphenation here, and make the space between Name Surname to be non-breakable?

I don't speak Hebrew though, maybe this is good as is

**Pull request merged**
