### PR TITLE
 Make setup image visible with enumeration 

### PR DESCRIPTION
**Pull request by DarthGandalf**
both

### CODE REVIEW

**Comment by qwrtln** [comment]
Nice and clean. I'll hijack your PR and carry on with this.

**Comment by qwrtln** [comment]
po4a check

**Comment by qwrtln** [comment]
po4a commit

**Comment by qwrtln** [comment]
po4a commit

**Review by qwrtln — APPROVED** [review]

**Review by Heegu-sama — APPROVED** [review]

**Pull request merged**
