### PR TITLE
Remove -shell-escape

### PR DESCRIPTION
**Pull request by DarthGandalf**
With noautomatic option of imakeidx it's not needed

### CODE REVIEW

**Comment by qwrtln** [comment]
Are you sure? It won't work if you're doing it for the first time. `-shell-escape` runs Inkscape, too.

**Review by qwrtln — CHANGES_REQUESTED** [review]
Try running it after `rm -rf svg-inkscape/`

**Comment by DarthGandalf** [comment]
Because the PR checks didn't fail, I thought it works :( But they didn't even try to run the build

**Comment by qwrtln** [comment]
> Because the PR checks didn't fail, I thought it works :( But they didn't even try to run the build

Yeah, build runs only on changed tex files and assets. Might need to rethink that approach.

**Pull request closed without merging**
