### PR TITLE
Address developer comment

### LINKED ISSUE #274: Trading post
Выделение_538

### PR DESCRIPTION
**Pull request by DarthGandalf**
Fix #274

both-39

### CODE REVIEW

**Comment by qwrtln** [comment]
Are you sure about this? My understanding was that you could do both, actually.

**Comment by qwrtln** [comment]
> Are you sure about this? My understanding was that you could do both, actually.

Even so, please update the description in all map locations too.

**Comment by Legrecofr** [comment]
If you read the core game rule of the trading post you can't do both it's say "or", In the Rampart rulebook buying war machines is added as a new option at the trading post. Meaning you can choose one from the 3 options.

**Review by qwrtln — APPROVED** [review]

**Comment by Heegu-sama** [comment]
image

I re-read the original and doesn't it actually also say that you can remove only one card?

**Review by evilmint — APPROVED** [review]

**Review by Heegu-sama — APPROVED** [review]

**Pull request merged**
