### PR TITLE
[FR] Last typos

### PR DESCRIPTION
**Pull request by Legrecofr**
@Gastonia02 Can you add the images please?

### CODE REVIEW

**Comment by Gastonia02** [comment]
po4a check

**Comment by Gastonia02** [comment]
po4a commit

**Comment by qwrtln** [comment]
FYI: updating your branch is now required. If you do that, there's no need for "CI Trigger" commit.

**Review by qwrtln — APPROVED** [review]

**Comment by qwrtln** [comment]
I noticed a fuzzy string in quotes page fr.po. Can you fix it?

**Comment by qwrtln** [comment]
@Gastonia02 Use this:
```bash
tools/find_fuzzy.sh fr
```

**Comment by qwrtln** [comment]
Ah, ignore me, you already fixed it, all good 👌🏻

**Comment by Legrecofr** [comment]
I was very tempted to replace the missing ")" by a croissant emoji but nobody would had the ref except you.

**Comment by qwrtln** [comment]
> I was very tempted to replace the missing ")" by a croissant emoji but nobody would had the ref except you.

I wonder if I would approve it ;-)

**Pull request merged**
