### PR TITLE
Expansion towns images

### PR DESCRIPTION
**Pull request by pastuh**
Suggestions to include image of towns that come with expansions

### CODE REVIEW

**Comment by qwrtln** [comment]
Please edit the document so that this image is included. Include images of changed pages in the PR description. Adding just the image has little sense.

**Comment by qwrtln** [comment]
Or, can you come up with an image which depicts all 7 Towns? Right now, Fortress would be left out.

**Comment by pastuh** [comment]
Updated image which includes all towns (in the order of publication). 
I believe someone else will be able to update the text by inserting this image as well.

**Comment by qwrtln** [comment]
Regarding your proposal with AI tools, I sure know nothing about them, but if you're willing to lead the initiative, I'm willing to help. Reach out to me on Discord, if you'd like to discuss it. My username over there is the same.

**Pull request closed without merging**
