### PR TITLE
Add AI Heroes chapter

### PR DESCRIPTION
**Pull request by qwrtln**
A proposal:

ai-35
ai-36

### CODE REVIEW

**Comment by Heegu-sama** [comment]
Looks great. I'll shuffle some of the information around, the AI card should be on the same page as where those cards are mentioned. Also, I should probably add more information about how the AI deck should be built using randomly chosen 'might' cards if there are any in the deck. As far as I know the ability/spell cards are all identical.

**Comment by Heegu-sama** [comment]
image
"Skill" AI card also has two variants. Here's a quick n dirty screencap of these cards just for reference.

**Comment by Heegu-sama** [comment]
image
Multicols drives me nuts. Mind fixing these @qwrtln ?

**Comment by qwrtln** [comment]
> image Multicols drives me nuts. Mind fixing these @qwrtln ?

Sure. Using `\vfill` instead of `\columnbreak` can do wonders. Needed to add better fitting art. How's that?

**Comment by qwrtln** [comment]
Also, there are hyperlinks to various AI rules in the introductory chapters. Mind checking if they're still valid?

**Pull request merged**
