### PR TITLE
[ES] fuzzy fix

### PR DESCRIPTION
**Pull request by luischos**
es-12
es-20
es-31
es-32
es-56

### CODE REVIEW

**Comment by DarthGandalf** [comment]
I see English text on bottom of page 20

**Comment by luischos** [comment]
oh, true, didn't see it

**Comment by luischos** [comment]
@DarthGandalf solved, but I don't understand the error with po4a...

**Comment by qwrtln** [comment]
po4a check

**Comment by qwrtln** [comment]
@luischos These are your uncommitted changes ☝🏻

**Comment by luischos** [comment]
po4a commit

**Comment by luischos** [comment]
po4a commit

**Review by DarthGandalf — APPROVED** [review]

**Pull request merged**
