### PR TITLE
Add index page to the printable build

### PR DESCRIPTION
**Pull request by qwrtln**
Index will be added to the printable build available through the README file. Adding new entries is as simple as typing `\index{...}` anywhere in the document, but preferably outside other commands.

PDF preview: https://index-rulebook.qwrtln.nl/main.pdf

Preview of the index page:

index-48

Got into a fixing frenzy and corrected some layout pain points too:

image

image

image

image

image

image

image

image

### CODE REVIEW

**Comment by qwrtln** [comment]
@RickardNi Please pay attention to capitalisation, as I found some inconsistencies around cards/Cards.

**Comment by RickardNi** [comment]
The preview link doesn't work for me.

Great that you added an index after suggestions on BGG. I'm glad that it's in the end and not the beginning.

I will check/fix all capitalizations and make judgement calls accordingly.

**Comment by qwrtln** [comment]
> The preview link doesn't work for me.
> 
> Great that you added an index after suggestions on BGG. I'm glad that it's in the end and not the beginning.
> 
> I will check/fix all capitalizations and make judgement calls accordingly.

Argh, I deleted that branch. The preview file is gone now. See it here: https://index-rulebook.qwrtln.nl/main.pdf

**Comment by RickardNi** [comment]
> Argh, I deleted that branch. The preview file is gone now. See it here: https://index-rulebook.qwrtln.nl/main.pdf

Great, thanks! It's nice to have, but not too necessary since I mainly look at the raw text files anyway.

I corrected some things in the Unit section so it should be good to go for this index branch. I have a list of more general changes that I'll try to fix soon.

**Review by RickardNi — APPROVED** [review]

**Review by Heegu-sama — APPROVED** [review]

**Pull request merged**
