### PR TITLE
[HE] town

### PR DESCRIPTION
**Pull request by davidpodless**
he-23

### CODE REVIEW

**Comment by qwrtln** [comment]
How about centering that town image?

**Comment by davidpodless** [comment]
No idea how to do it

I've tried to add a lot of enters but it didn't work...

is there a magic way to do it?

**Comment by DarthGandalf** [comment]
Yeah, enters won't do much. You can try to add `\vfill` above and below the image

**Comment by davidpodless** [comment]
well, the secret was to add \columnbreak at the end of the text

he-23

**Comment by davidpodless** [comment]
ping
@qwrtln @DarthGandalf

**Review by DarthGandalf — APPROVED** [review]

**Review by qwrtln — APPROVED** [review]

**Pull request merged**
