### PR TITLE
Clarify exiting blocked fields

### PR DESCRIPTION
**Pull request by DarthGandalf**
This is what official rules say about this:

> This is a special kind of terrain that Heroes cannot enter.

Some scenarios spawn enemy heroes there, and with rewritten rules as written, they would be stuck there.

en-both-22

When combined with #278:
en-both-22

### CODE REVIEW

**Comment by qwrtln** [comment]
Where does it say you cannot exit them?

**Comment by DarthGandalf** [comment]
In the left column: "solid yellow lines cannot be passed through"

**Comment by qwrtln** [comment]
> In the left column: "solid yellow lines cannot be passed through"

In that case, the not box is not accurate. You can pass them using skills or spells. Maybe this should be a regular text, not a box?

**Comment by DarthGandalf** [comment]
Well, intro already states that what's written on player cards overrides the rules. How do you suggest wording this and where?

This is so corner case, that I thought the note near the place where blocked fields are mention at all would be more appropriate than interrupting the flow of text

**Comment by DarthGandalf** [comment]
But it's not obvious from this "normally" whether player hero can go inside to attack the enemy hero. It's obvious from the official book - it cannot.

**Review by Heegu-sama — APPROVED** [review]

**Comment by qwrtln** [comment]
po4a check

**Comment by DarthGandalf** [comment]
po4a commit

**Pull request merged**
