### PR TITLE
[CS] setup

### PR DESCRIPTION
**Pull request by tomaas-zeman**
en-08
en-09
en-10

### CODE REVIEW

**Comment by qwrtln** [comment]
Please download a fresh PDF file and compare the matching version, not digital against printable.

**Review by qwrtln — APPROVED** [review]

**Comment by tomaas-zeman** [comment]
> Please download a fresh PDF file and compare the matching version, not digital against printable. You can use the script like that: `tools/compare_pages.sh <downloaded_en_pdf> cs 8 10`

That's what I did, I just accidentally overwrote my downloaded file with printable version. Fixed now

**Comment by DarthGandalf** [comment]
@tomaas-zeman are you in discord? we should to add you to the translators chat

**Comment by tomaas-zeman** [comment]
> @tomaas-zeman are you in discord? we should to add you to the translators chat

Yes. Discord name is `tomas.zeman`

**Pull request merged**
