### PR TITLE
New SP clarification

### PR DESCRIPTION
**Pull request by DarthGandalf**
en-20

### CODE REVIEW

**Comment by DerSchlupf** [comment]
Nice Addition IMO!

**Review by DerSchlupf — APPROVED** [review]

**Comment by qwrtln** [comment]
Does it have to be a box? Having it as a last sentence of the paragraph would be clearer, shorter, and wouldn't disrupt the flow of text:
image

**Comment by DarthGandalf** [comment]
@qwrtln True. Could you push that?

I made it the box because such rule would be relevant very rarely, making it into Exceptions category

**Comment by qwrtln** [comment]
I don't consider it an exception. I guess it's implicitly obvious to most people, but it should be enough for those complaining that they can't get gold from View Air, if they have Air Magic on the table.

**Review by qwrtln — APPROVED** [review]

**Review by Heegu-sama — APPROVED** [review]
Nice clarification. I assume this was confirmed on discord/BGG at some point.

**Comment by DarthGandalf** [comment]
Yep, https://discord.com/channels/740870068178649108/1211591995328299038/1305812432543023146

**Comment by qwrtln** [comment]
Was merging this necessary? Now every translation is fuzzy.

**Comment by DarthGandalf** [comment]
Would you prefer to update all the translations before merging?

**Comment by qwrtln** [comment]
No, release 1.3 first. We had 7 languages fit for release. Now we have 1.

**Comment by DarthGandalf** [comment]
Hm, right.

let me prepare rollback then

**Comment by qwrtln** [comment]
Not sure why people are so attached to releases, but I keep seeing them using the old 1.2 PDF.

**Pull request merged**
