### PR TITLE
[ES] printable bugs

### PR DESCRIPTION
**Pull request by luischos**
Finally, all translated correctly and well put together.

### CODE REVIEW

**Comment by luischos** [comment]
Can't attach the PDFs, they are to heavy

**Comment by luischos** [comment]
No, It's not, 52 pages, I have created it right now merged with main

**Comment by luischos** [comment]
I think the problem is about the font style, or font size, from my Local and Git, is not the same, the PDFs are the same but haven't the same style, and this make an extra page.

**Comment by luischos** [comment]
It's solved :D

**Review by qwrtln — APPROVED** [review]

**Pull request merged**
