### PR TITLE
Add note box custom command

### PR DESCRIPTION
**Pull request by qwrtln**
This introduces Heroes III themed boxes to all the "notes" and "importants". 

You can see the whole PDF here: https://notes-rulebook.qwrtln.nl/main.pdf

Some examples:

image

image

image

### CODE REVIEW

**Comment by qwrtln** [comment]
This might need yellowish-colored glyphs. Black ones are badly visible.

**Review by RickardNi — APPROVED** [review]

**Comment by csagataj2** [comment]
Have you considered using a single background note image and using horizontal scaling to better fit the text? I think it would be nicer

**Comment by qwrtln** [comment]
> Have you considered using a single background note image and using horizontal scaling to better fit the text? I think it would be nicer

I haven't. What are you suggesting, exactly? Stretching the image vertically if the text doesn't fit?

**Comment by qwrtln** [comment]
BTW, @csagataj2, would you be able to produce some glyphs in this yellowish colour? Its definition is `{rgb}{0.91, 0.84, 0.42}`, and the glyphs are `necro.svg`, `movement_tokens.svg`, `unit_attack.svg` and `instant.svg`.

**Comment by qwrtln** [comment]
Was also thinking about azure star with this yellowish border, because it looks hidden :D
image

**Comment by qwrtln** [comment]
Never mind, Inkscape is not so hard to use.

image

**Comment by Heegu-sama** [comment]
> Never mind, Inkscape is not so hard to use.
> 
> image

Are you adding these glyphs to this PR?

**Comment by csagataj2** [comment]
> > Have you considered using a single background note image and using horizontal scaling to better fit the text? I think it would be nicer
> 
> I haven't. What are you suggesting, exactly? Stretching the image vertically if the text doesn't fit?

Yeah, I meant vertical scaling, sorry for the confusion. This was my suggestion.

**Comment by qwrtln** [comment]
> > > Have you considered using a single background note image and using horizontal scaling to better fit the text? I think it would be nicer
> > 
> > 
> > I haven't. What are you suggesting, exactly? Stretching the image vertically if the text doesn't fit?
> 
> Yeah, I meant vertical scaling, sorry for the confusion. This was my suggestion.

I didn't try it, but I figured, since some of the box text is more than twice as long as for the shorter ones, a stretched-out box like that wouldn't look nice. What do you think about it?

**Comment by qwrtln** [comment]
An example with hyperlink and changed glyph:
image

**Comment by csagataj2** [comment]
> > > > Have you considered using a single background note image and using horizontal scaling to better fit the text? I think it would be nicer
> > > 
> > > 
> > > I haven't. What are you suggesting, exactly? Stretching the image vertically if the text doesn't fit?
> > 
> > 
> > Yeah, I meant vertical scaling, sorry for the confusion. This was my suggestion.
> 
> I didn't try it, but I figured, since some of the box text is more than twice as long as for the shorter ones, a stretched-out box like that wouldn't look nice. What do you think about it?

I will try to think about this topic and come up with a solution. But do not wait for this, we can fix in a future PR.

**Review by Heegu-sama — APPROVED** [review]

**Pull request merged**
