### PR TITLE
[ES] Back Cover and Difficulty Bug

### PR DESCRIPTION
**Pull request by luischos**

### CODE REVIEW

**Review by qwrtln — CHANGES_REQUESTED** [review]
In optional rules table the left column with variants is not aligned with the content properly. Please fix it.

**Comment by luischos** [comment]
Eagle eye lol
Solved :)

**Comment by qwrtln** [comment]
Please post a new picture. Which PDF reader are you using for this. This black outline around the starts is surprisingly thick.

**Comment by luischos** [comment]
Images Updated. I use Chrome to view the PDFs (I have not another PDF reader installed right now).

**Review by qwrtln — APPROVED** [review]

**Pull request merged**
