### PR TITLE
[CS] Added translations for combat priority; Magic arrow is more consistent

### PR DESCRIPTION
**Pull request by Daar543**
Edit: I have trouble with MikTex so I was not able to fully generate the pdf to show the images, hopefully full reinstall will help.

Combat priority for ranged units translation
Secondary hero flee translation
Changed Magic Arrow for Magický šíp across all translations (same as on card)
Clarified "trade" between players
Changed Impossible to Nehratelná (same as in game)
Redwood Observatory is translated to "normal" Czech (Sekvojová rozhledna)

### CODE REVIEW

**Comment by tomaas-zeman** [comment]
Thanks for the corrections! Keep them coming, you're the first guy validating the Czech translation really :) 

Additionally, this could be "Nehratelný modifikátor" https://github.com/Heegu-sama/Homm3BG/blob/main/translations/ai_rules.tex/cs.po#L171

**Comment by tomaas-zeman** [comment]
po4a commit

**Review by tomaas-zeman — APPROVED** [review]

**Comment by Daar543** [comment]
> To fix the failing pipeline, you need to run po4a -v po4a.cfg and commit the changes

I have this error:
```$ po4a -v po4a.cfg
Split mode, creating a temporary POT:sections/ai_rules.tex:53: (po4a::tex)
               unmatched end of environment 'multicols*'
Unknown encoding '' at /usr/share/perl5/Locale/Po4a/TransTractor.pm line 1004.
```

By the way the English version (with `tools/build.sh en` ) does work normally. The multicols* was occuring there too but compilation was succesful, so does not seem like the main error.
On ubuntu I got only to version 0.66 with po4a which might seem like an error too.

**Comment by tomaas-zeman** [comment]
> > To fix the failing pipeline, you need to run po4a -v po4a.cfg and commit the changes
> 
> Okay I have fixed that, needed to install the newest po4a.
> 
> > Keep them coming, you're the first guy validating the Czech translation really
> 
> Thanks! I am no expert, I just went for the obvious mistakes. What I have issue with is the board game translation itself, not sure if they wanted to be original and take creative liberties as the 2020 translation did on the video game (compared to the initial one I grew up with), or they were really clueless how they were called in Czech and made it up on the spot. But I do not wanna to dig into it too much :)

I was not sure about that either. But the official Czech translation sounds very weird to me so I took the liberty to change some of it. But in the end, I used chat GPT to do the heavy lifting but never did a second pass to unify and correct terms here and there

**Comment by qwrtln** [comment]
What are all those additional tex files for?

**Pull request merged**
