### PR TITLE
[HE] introduction

### PR DESCRIPTION
**Pull request by davidpodless**
Something strange that happened now
I need to add \\texthebrew inside notes and addsection, without it it doesn't print anything.

A little bit annoying, but nothing that can't be handle inside the translation itself

### CODE REVIEW

**Comment by davidpodless** [comment]
image

**Comment by qwrtln** [comment]
Please, post the whole page. You can use `tools/pdf2image.sh` script for this.

**Comment by davidpodless** [comment]
> Please, post the whole page. You can use `tools/pdf2image.sh` script for this.

it doesn't work in my machine. (probably missing few libs/softwares)
 but ok, I'll printscreen the whole page

**Review by DarthGandalf — APPROVED** [review]

**Comment by qwrtln** [comment]
> Please, post the whole page. You can use `tools/pdf2image.sh` script for this.

That's just one utility. Install `pdftoppm` and you're good to go.

**Comment by davidpodless** [comment]
> > Please, post the whole page. You can use `tools/pdf2image.sh` script for this.
> 
> That's just one utility. Install `pdftoppm` and you're good to go.

I haven't seen it in brew 😕

**Comment by qwrtln** [comment]
> > > Please, post the whole page. You can use `tools/pdf2image.sh` script for this.
> > 
> > 
> > That's just one utility. Install `pdftoppm` and you're good to go.
> 
> I haven't seen it in brew 😕

`brew install poppler`

**Pull request merged**
